{:npm-deps {"@radix-ui/react-dropdown-menu" "^2.0.6",
            "@radix-ui/react-icons" "^1.3.0",
            "@radix-ui/react-popover" "^1.0.7",
            "@radix-ui/react-toggle" "^1.0.3",
            "@radix-ui/react-toolbar" "^1.0.4",
            "@tiptap/extension-link" "^2.3.0",
            "@tiptap/extension-mention" "^2.3.0",
            "@tiptap/extension-task-item" "^2.3.0",
            "@tiptap/extension-task-list" "^2.3.0",
            "@tiptap/pm" "^2.3.0",
            "@tiptap/react" "^2.3.0",
            "@tiptap/starter-kit" "^2.3.0",
            "@tiptap/suggestion" "^2.3.0",
            "html-react-parser" "^5.1.10",
            "react" "^18.2.0",
            "react-dom" "^18.2.0",
            "shadow-cljs" "^2.28.3"}}
